function [vidOut] = generateStdVideo3DFunc(vidIn,Params)

root = getenv('TemporalSegmentation');
addpath(genpath([root,'/utils']));

resizeFactors = Params.resizeFactors;
vidIn = safeResize(int8(vidIn), resizeFactors.*size(vidIn));
elevationHalfAngle = atand(tand(Params.elevationHalfAngle) * resizeFactors(1) / resizeFactors(3));

vid_std = ...
    computeCombinedStd_IN3D(vidIn, ...
    Params.azimuthNum, ...
    Params.elevationNum, ...
    elevationHalfAngle, ...
    Params.numOfScales, ...
    Params.sigmaSpatial, ...
    Params.sigmaTemporal, ...
    Params.m1, ...
    Params.m2, ...
    Params.normQ ...
    );

vid_std_squared = sign(vid_std).*(vid_std.^2);
vidOut = minMaxNorm(vid_std_squared);
end

