function [vidOut] = generateStdVideo3DFunc(vidIn,Params)

root = getenv('TemporalSegmentation');
addpath(genpath([root,'/utils']));

resizeFactors = Params.resizeFactors;
vidIn = safeResize(int8(vidIn), resizeFactors.*size(vidIn));
elevationHalfAngle = atand(tand(Params.elevationHalfAngle) * resizeFactors(1) / resizeFactors(3));

saveSnapshots(vidIn, Params.snapshotDir, 'resized_input');

vid_std = ...
    computeCombinedStd_IN3D(vidIn, ...
    Params.azimuthNum, ...
    Params.elevationNum, ...
    elevationHalfAngle, ...
    Params.numOfScales, ...
    Params.spatialVar, ...
    Params.temporalVar, ...
    Params.m1, ...
    Params.m2, ...
    Params.normQ, ...
    Params.snapshotDir ...
    );

vid_std_magnified = sign(vid_std).*(abs(vid_std).^Params.powerFactor);
vidOut = minMaxNorm(vid_std_magnified);

end

