function [vid_in,vid_out] = detailEnhancement3Dfunc(vid_in,Params,verbose)

%TODO: check input validity to structs
%TODO: merge with computecombinedLF
resizeFactors = Params.resizeFactors;

vid_in = safeResize(vid_in, resizeFactors.*size(vid_in));
elevationHalfAngle = atand(tand(Params.elevationHalfAngle) * resizeFactors(1) / resizeFactors(3));

vid_out = ...
    computeCombinedLf3d(vid_in, ...
    Params.azimuthNum, ...
    Params.elevationNum, ... 
    elevationHalfAngle, ...
    Params.eccentricity, ...
    Params.numOfScales , ...
    Params.activationThreshold, ...
    Params.facilitationLengths, ... 
    Params.alpha, ... 
    Params.m1, ...
    Params.m2, ...
    Params.normQ ...
    );

if verbose 
    normFactor = max(abs(vid_out),[],'all');
    vidDisp = vid_out./(2*normFactor) +1/2;
    implay(vidDisp)
    maintainFitToWindow();
    disp(['max abs  = ',normFactor])
end

end

